### ISSUE TITLE
Add UAVCAN logo to README

### ISSUE THREAD

**Issue by aentinger** [107-systems/107-Arduino-UAVCAN#100]
@pavel-kirienko would that be okay?

**Comment by pavel-kirienko** [comment]
Of course. We only regulate usage of the UAVCAN Conformity Mark --- using that without permission would be illegal, but the regular UAVCAN logo can be used freely. We also have sick ASCII art:

```
 __   __   _______   __   __   _______   _______   __   __
|  | |  | /   _   ` |  | |  | /   ____| /   _   ` |  ` |  |
|  | |  | |  |_|  | |  | |  | |  |      |  |_|  | |   `|  |
|  |_|  | |   _   | `  `_/  / |  |____  |   _   | |  |`   |
`_______/ |__| |__|  `_____/  `_______| |__| |__| |__| `__|
    |      |            |         |      |         |
----o------o------------o---------o------o---------o-------
```

**Comment by aentinger** [comment]
That's pretty neat :wink: I think I've found the UAVCAN logo in [eps](https://github.com/UAVCAN/specification/blob/master/specification/uavcan_logo.eps) ... can you point me towards a JPG/PNG version?

**Comment by pavel-kirienko** [comment]
We only have SVG here: https://github.com/UAVCAN/uavcan.org/blob/master/app/static/images/logo.svg
