### ISSUE TITLE
Possible bug in ARDUINO_UAVCAN_TYPES_UAVCAN_REGISTER_LIST_1_0_HPP_

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-UAVCAN#152]
https://github.com/107-systems/107-Arduino-Cyphal/blob/d1b09ae0eb1151e64b656e125742f48c8a4fc24f/src/wrappers/uavcan/register/List_1_0.hpp#L78

shouldn't this be:

`static constexpr CanardTransferKind TRANSFER_KIND = CanardTransferKindResponse;`

**Comment by aentinger** [comment]
Good catch. We should really invest in auto-generating those wrapper files via some tooling :pray:
