### ISSUE TITLE
Extending DSDL

### ISSUE THREAD

**Issue by not7cd** [107-systems/107-Arduino-UAVCAN#205]
What is the recommended way to add project-specific Cyphal type definitions? Considering that I have a structure similar to https://github.com/OpenCyphal/public_regulated_data_types how do I generate those types and use them with this library?

**Comment by aentinger** [comment]
This can be done with [nunavut](https://github.com/OpenCyphal/nunavut). However, GitHub issues are not there for support requests, please head on over to the [OpenCyphal forum](https://forum.opencyphal.org/), post your question there, and put the link in this thread.

That way, the next person wondering this may also profit.

**Comment by not7cd** [comment]
I sure will do that. But it doesn't solve my question specific to this library. Should I give output directory as `src/types` or `.pio/libdeps/pico/107-Arduino-Cyphal/src/types`

**Comment by aentinger** [comment]
Yes. But as I wrote before, this is not the place for support. The forum is. I'll answer you over there. Not here.

**Comment by not7cd** [comment]
backref: [Using custom DSDL with 107-Arduino-OpenCyphal and PIO - Applications & Usage / Nunavut - OpenCyphal Forum](https://forum.opencyphal.org/t/using-custom-dsdl-with-107-arduino-opencyphal-and-pio/1830)
