### ISSUE TITLE
[Feature Request] Request support for esp32

### ISSUE THREAD

**Issue by dwaipayanb1994** [107-systems/107-Arduino-UAVCAN#237]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request

**Please Describe The Problem To Be Solved**
Hello, I'm unable to compile this for Esp32 due to missing libs like span in esp32 g++. Could you please add the support for Esp32.

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by aentinger** [comment]
No. You may do it yourself or you can book a private consulting engagement.

**Comment by walnut-engineering** [comment]
Was esp32 supported and then dropped?  Reference: https://forum.opencyphal.org/t/107-arduino-uavcan-with-esp32/1096
