### ISSUE TITLE
Update wiki to instruct users to edit the nunavut generated header files due to include path 

### ISSUE THREAD

**Issue by echoGee** [107-systems/107-Arduino-UAVCAN#94]
https://github.com/107-systems/107-Arduino-UAVCAN/wiki has intructions to make header files. But the instructions to edit the header files need to be added for completeness and accuracy

**Comment by pavel-kirienko** [comment]
It would also be nice to link http://nunaweb.uavcan.org

**Comment by aentinger** [comment]
I think you can both see that the wiki is currently more a personal reminder than for general consumption :wink: Would one of you be able to supply a first draft?

**Comment by echoGee** [comment]
Draft of ?

**Comment by aentinger** [comment]
I meant a draft of desirable documentation. I'm going to be honest, I'm currently drowning in work. Consequently the wiki documentation is quite low on priority. Furthermore, this specific bit of information (that is how to add new wrappers) is quite important so it might end up being moved to the README instead. If one of you does have the time or the drive to write that up then please be my guest, as I fear I won't get to it anytime soon.
